CREATE TABLE IF NOT EXISTS `{prefix}forms` (
  `id`               INT(11)         NOT NULL AUTO_INCREMENT,
  `status`           ENUM ('0', '1') NOT NULL DEFAULT '1',
  `date`             DATETIME        NOT NULL,
  `type`             VARCHAR(10)     NOT NULL DEFAULT 'form',
  `template`         VARCHAR(20)     NOT NULL,
  `in_out`           ENUM ('0', '1') NOT NULL DEFAULT '1',
  `account_id`       INT(11)         NOT NULL,
  `account_code`     VARCHAR(32)     NOT NULL,
  `account_name`     VARCHAR(50)     NOT NULL,
  `account_gsm`      VARCHAR(20)     NOT NULL,
  `account_phone`    VARCHAR(20)     NOT NULL,
  `account_email`    VARCHAR(100)    NOT NULL,
  `account_city`     VARCHAR(20)     NOT NULL,
  `account_tax_home` VARCHAR(20)     NOT NULL,
  `account_tax_no`   VARCHAR(20)     NOT NULL,
  `total`            DECIMAL(15, 4)  NOT NULL,
  `profit`           DECIMAL(15, 4)  NOT NULL,
  `payment`          DECIMAL(15, 4)  NOT NULL,
  `item_count`       INT(11)         NOT NULL,
  `item_quantity`    INT(11)         NOT NULL,
  `status_id`        INT(11)         NOT NULL,
  `user_id`          INT(11)         NOT NULL,
  `date_updated`     DATETIME        NOT NULL,
  `val_1`            VARCHAR(255)    NOT NULL,
  `val_2`            VARCHAR(512)    NOT NULL,
  `val_3`            VARCHAR(1024)   NOT NULL,
  `val_int`          INT(11)         NOT NULL,
  `val_date`         DATETIME        NOT NULL,
  `val_decimal`      DECIMAL(15, 4)  NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;